### ISSUE TITLE
Recieve an ArgumentOutOfRange on PlayerSelect Scene

### ISSUE THREAD

**Issue by kmayo3** [gbohnen/GDD3000-ThinBlueLine#35]
Didn't seem to mess up the code, I could still select all four players and they went through to the next scene.

Just check this out to see what this is. Maybe a silly error. I've attached a picture of it below. 
![argumenterror](https://cloud.githubusercontent.com/assets/8864798/20774450/8f48ad68-b713-11e6-99c7-3e2ee5e46fca.PNG)

**Comment by gbohnen** [comment]
This error is not game-breaking. Simple list index issue. Given time, I'll run through and make sure it's fixed.
