### ISSUE TITLE
Text on PlayerSelect scene

### ISSUE THREAD

**Issue by kmayo3** [gbohnen/GDD3000-ThinBlueLine#36]
The font throughout the PlayerSelect screen is different for each section.

Sometimes  the descriptions are so long that it causes the font to be extremely small. (sometimes illegible) We need to fix the size of the font or cut off some of the descriptions so it looks nicer.

**Comment by gbohnen** [comment]
Note: Add task to have Isaac or Wes shorten text that will leave the text size too small

**Comment by kmayo3** [comment]
Added a task for Wes. Due date is by Saturday. Should be done by then. Closing issue.
