### ISSUE TITLE
Consistent Wording on the UI

### ISSUE THREAD

**Issue by kmayo3** [gbohnen/GDD3000-ThinBlueLine#39]
For example, a situation card displays a Positive Resolution and a Negative Resolution - both of these descriptions either say No Positive Outcome or No Negative Outcome.

Also, both the Immediate Effect & Ongoing Effect have parentheses behind them to hint at what moment they will go into effect. The Positive & Negative Resolutions do not. 

The UI needs to be more consistent in what it displays. 

See the photo below. 
![situationcard](https://cloud.githubusercontent.com/assets/8864798/20774841/6f580d94-b715-11e6-937b-7b5d5cbe3ace.PNG)

**Comment by gbohnen** [comment]
Negative outcome has been removed, and the positive resolution has been given a similar parenthetical tag
