### ISSUE TITLE
Selected Buttons can still be selected again under Situations Tab

### ISSUE THREAD

**Issue by kmayo3** [gbohnen/GDD3000-ThinBlueLine#40]
You can select the button for the neighborhood you are in causing it to turn black. Which I think is odd. If we are in that neighborhood we should not be able to select that button again until we are in a different one trying to get back. So just make that button inactive if it is selected. 

![blackbutton](https://cloud.githubusercontent.com/assets/8864798/20775147/c454c5ca-b716-11e6-936c-80a785c7ad9a.PNG)

**Comment by gbohnen** [comment]
The buttons have been correctly set to disable navigation. The neighborhood is still clickable, but will not be "stuck" colored black.
