### ISSUE TITLE
Have no way to tell what neighborhood I am in

### ISSUE THREAD

**Issue by kmayo3** [gbohnen/GDD3000-ThinBlueLine#42]
There are indicators, but I have already forgotten which is mine so I do not know which one I am in. Maybe the colors should match the indicator on the left (which now need to change when players do) or the colors should be much different from each other. OR they can all be black and just highlight whenever that player is up.

**Comment by gbohnen** [comment]
Each player corresponds to the tab position. Player 1 is the topmost tab, Player 4 is the bottom most. I can include small numbers in the indicators to describe which player position they indicate.

**Comment by kmayo3** [comment]
I'd like the indicator on the left to be the same colors as the one on the right or yeah I guess you could put numbers on it. But, since there are not any numbers like that indicated anywhere else in the game I don't really see that as a solution.

**Comment by gbohnen** [comment]
New player pieces added to the board. This issue should be resolved.
