### ISSUE TITLE
Can solve situation in any neighborhood

### ISSUE THREAD

**Issue by kmayo3** [gbohnen/GDD3000-ThinBlueLine#45]
even if the player is not in that neighborhood. I figured the reason for neighborhoods was that you had to be in a specific one to deal with its situations. Is this wrong?

**Comment by gbohnen** [comment]
This is unintended behavior. TODO: Add a check that ensures only local situations can be resolved.

**Comment by gbohnen** [comment]
Situations no longer respond if the player neighborhood and situation manager don't match.
