### ISSUE TITLE
Major Crime UI

### ISSUE THREAD

**Issue by kmayo3** [gbohnen/GDD3000-ThinBlueLine#73]
The spacing is off and everything seems to be shifted around

![ui](https://cloud.githubusercontent.com/assets/8864798/21092794/b3bb59e2-c00b-11e6-9b01-f1be135787f2.PNG)

**Comment by gbohnen** [comment]
This has been manually fixed for the Bank Heist crime. The extra whitespace will need to be removed from other Crimes for further development.
